"""Agent personal contact channels. Idempotent SQLite + Postgres."""

from __future__ import annotations

from modules.config import BACKEND_POSTGRES, get_database_backend
from modules.database.connection import get_connection


SQLITE_DDL = """
CREATE TABLE IF NOT EXISTS agent_contact_channels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL,
    agent_id INTEGER NOT NULL,
    whatsapp_number TEXT,
    whatsapp_enabled INTEGER NOT NULL DEFAULT 0,
    whatsapp_connected_at TEXT,
    instagram_handle TEXT,
    instagram_enabled INTEGER NOT NULL DEFAULT 0,
    instagram_connected_at TEXT,
    updated_at TEXT,
    UNIQUE (organization_id, agent_id),
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
)
"""

POSTGRES_DDL = """
CREATE TABLE IF NOT EXISTS agent_contact_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    agent_id BIGINT NOT NULL,
    whatsapp_number TEXT,
    whatsapp_enabled SMALLINT NOT NULL DEFAULT 0,
    whatsapp_connected_at TEXT,
    instagram_handle TEXT,
    instagram_enabled SMALLINT NOT NULL DEFAULT 0,
    instagram_connected_at TEXT,
    updated_at TEXT,
    UNIQUE (organization_id, agent_id),
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
)
"""


def _sqlite_column_exists(cursor, table_name, column_name):
    cursor.execute(f"PRAGMA table_info({table_name})")
    return any(row[1] == column_name for row in cursor.fetchall())


def migrate_agent_contact_channels_sqlite():
    connection = get_connection()
    try:
        cursor = connection.cursor()
        cursor.execute(SQLITE_DDL)
        if not _sqlite_column_exists(cursor, "agents", "whatsapp_number"):
            cursor.execute("ALTER TABLE agents ADD COLUMN whatsapp_number TEXT")
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def migrate_agent_contact_channels_postgres(cursor):
    cursor.execute(POSTGRES_DDL)
    cursor.execute(
        "ALTER TABLE agents ADD COLUMN IF NOT EXISTS whatsapp_number TEXT"
    )


def migrate_agent_contact_channels():
    if get_database_backend() == BACKEND_POSTGRES:
        connection = get_connection()
        try:
            cursor = connection.cursor()
            migrate_agent_contact_channels_postgres(cursor)
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()
        return
    migrate_agent_contact_channels_sqlite()
