"""Audit rows for commercial status and price changes made from a visit close."""

from __future__ import annotations

from modules.config import BACKEND_POSTGRES, get_database_backend
from modules.database.connection import get_connection


SQLITE_DDL = """
CREATE TABLE IF NOT EXISTS property_commercial_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL,
    property_id INTEGER NOT NULL,
    actor_user_id INTEGER,
    agent_id INTEGER,
    task_id INTEGER,
    previous_commercial_status TEXT,
    commercial_status TEXT NOT NULL,
    previous_price REAL,
    previous_currency TEXT,
    listing_price REAL,
    listing_currency TEXT,
    reservation_amount INTEGER,
    reservation_currency TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
    FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE RESTRICT
)
"""

POSTGRES_DDL = """
CREATE TABLE IF NOT EXISTS property_commercial_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    actor_user_id BIGINT,
    agent_id BIGINT,
    task_id BIGINT,
    previous_commercial_status TEXT,
    commercial_status TEXT NOT NULL,
    previous_price DOUBLE PRECISION,
    previous_currency TEXT,
    listing_price DOUBLE PRECISION,
    listing_currency TEXT,
    reservation_amount INTEGER,
    reservation_currency TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
    FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE RESTRICT
)
"""

INDEXES = (
    "CREATE INDEX IF NOT EXISTS idx_property_commercial_events_property "
    "ON property_commercial_events (organization_id, property_id, id)",
)


def migrate_property_commercial_events_sqlite():
    connection = get_connection()
    try:
        cursor = connection.cursor()
        cursor.execute(SQLITE_DDL)
        for statement in INDEXES:
            cursor.execute(statement)
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def migrate_property_commercial_events_postgres(cursor):
    cursor.execute(POSTGRES_DDL)
    for statement in INDEXES:
        cursor.execute(statement)


def migrate_property_commercial_events():
    if get_database_backend() == BACKEND_POSTGRES:
        connection = get_connection()
        try:
            cursor = connection.cursor()
            migrate_property_commercial_events_postgres(cursor)
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()
        return
    migrate_property_commercial_events_sqlite()
