"""Public property and shortlist links. Idempotent SQLite + Postgres."""

from __future__ import annotations

from modules.config import BACKEND_POSTGRES, get_database_backend
from modules.database.connection import get_connection


SQLITE_STATEMENTS = (
    """
CREATE TABLE IF NOT EXISTS property_public_links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL,
    property_id INTEGER NOT NULL,
    token TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    revoked_at TEXT,
    created_by_agent_id INTEGER,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
    FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE RESTRICT
)
""",
    """
CREATE TABLE IF NOT EXISTS public_shortlists (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL,
    contact_id INTEGER,
    token TEXT NOT NULL UNIQUE,
    property_ids_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    revoked_at TEXT,
    created_by_agent_id INTEGER,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT
)
""",
    """
CREATE TABLE IF NOT EXISTS public_share_opens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL,
    kind TEXT NOT NULL,
    link_id INTEGER NOT NULL,
    opened_at TEXT NOT NULL,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT
)
""",
)

POSTGRES_STATEMENTS = (
    """
CREATE TABLE IF NOT EXISTS property_public_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    token TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    revoked_at TEXT,
    created_by_agent_id BIGINT,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
    FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE RESTRICT
);
""",
    """
CREATE TABLE IF NOT EXISTS public_shortlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    contact_id BIGINT,
    token TEXT NOT NULL UNIQUE,
    property_ids_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    revoked_at TEXT,
    created_by_agent_id BIGINT,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT
);
""",
    """
CREATE TABLE IF NOT EXISTS public_share_opens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    kind TEXT NOT NULL,
    link_id BIGINT NOT NULL,
    opened_at TEXT NOT NULL,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT
);
""",
)

INDEXES = (
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_property_public_links_one_active "
    "ON property_public_links (organization_id, property_id) WHERE status = 'active'",
    "CREATE INDEX IF NOT EXISTS idx_property_public_links_token "
    "ON property_public_links (token)",
    "CREATE INDEX IF NOT EXISTS idx_public_shortlists_token "
    "ON public_shortlists (token)",
    "CREATE INDEX IF NOT EXISTS idx_public_share_opens_link "
    "ON public_share_opens (organization_id, kind, link_id)",
)


def _apply(cursor, statements):
    for statement in statements:
        cursor.execute(statement)
    for statement in INDEXES:
        cursor.execute(statement)


def migrate_public_share_sqlite():
    connection = get_connection()
    try:
        _apply(connection.cursor(), SQLITE_STATEMENTS)
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def migrate_public_share_postgres(cursor):
    _apply(cursor, POSTGRES_STATEMENTS)


def migrate_public_share():
    if get_database_backend() == BACKEND_POSTGRES:
        connection = get_connection()
        try:
            migrate_public_share_postgres(connection.cursor())
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()
        return
    migrate_public_share_sqlite()
