"""Push notification subscriptions. Idempotent SQLite + Postgres."""

from __future__ import annotations

from modules.config import BACKEND_POSTGRES, get_database_backend
from modules.database.connection import get_connection


SQLITE_DDL = """
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    endpoint TEXT NOT NULL,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    user_agent TEXT,
    device_label TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT,
    updated_at TEXT,
    last_success_at TEXT,
    last_failure_at TEXT,
    UNIQUE (endpoint),
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)
"""

POSTGRES_DDL = """
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    endpoint TEXT NOT NULL,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    user_agent TEXT,
    device_label TEXT,
    is_active SMALLINT NOT NULL DEFAULT 1,
    created_at TEXT,
    updated_at TEXT,
    last_success_at TEXT,
    last_failure_at TEXT,
    UNIQUE (endpoint),
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)
"""

SQLITE_INDEXES = (
    "CREATE INDEX IF NOT EXISTS idx_push_subscriptions_org_user ON push_subscriptions (organization_id, user_id)",
    "CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_active ON push_subscriptions (user_id, is_active)",
)

POSTGRES_INDEXES = SQLITE_INDEXES


def migrate_push_subscriptions_sqlite():
    connection = get_connection()
    try:
        cursor = connection.cursor()
        cursor.execute(SQLITE_DDL)
        for statement in SQLITE_INDEXES:
            cursor.execute(statement)
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def migrate_push_subscriptions_postgres(cursor):
    cursor.execute(POSTGRES_DDL)
    for statement in POSTGRES_INDEXES:
        cursor.execute(statement)


def migrate_push_subscriptions():
    if get_database_backend() == BACKEND_POSTGRES:
        connection = get_connection()
        try:
            cursor = connection.cursor()
            migrate_push_subscriptions_postgres(cursor)
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()
        return
    migrate_push_subscriptions_sqlite()
