"""Reservations, notes, documents, and audit events. SQLite REAL matches listing_price; Postgres uses NUMERIC(18, 4)."""

from __future__ import annotations

from modules.config import BACKEND_POSTGRES, get_database_backend
from modules.database.connection import get_connection


_MONEY_PG = "NUMERIC(18, 4)"

SQLITE_TABLES = (
    """
    CREATE TABLE IF NOT EXISTS reservations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        organization_id INTEGER NOT NULL,
        property_id INTEGER NOT NULL,
        contact_id INTEGER,
        agent_id INTEGER,
        visit_id INTEGER,
        operation_id INTEGER,
        reservation_status TEXT NOT NULL,
        original_property_price REAL,
        original_currency TEXT,
        agreed_property_price REAL,
        agreed_currency TEXT,
        reservation_amount REAL,
        reservation_currency TEXT,
        payment_method TEXT,
        next_milestone TEXT,
        estimated_closing_date TEXT,
        notes TEXT,
        reserved_at TEXT NOT NULL,
        price_decision TEXT,
        cancelled_by_user_id INTEGER,
        cancelled_at TEXT,
        created_by_user_id INTEGER,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE RESTRICT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reservation_notes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        organization_id INTEGER NOT NULL,
        reservation_id INTEGER NOT NULL,
        body TEXT NOT NULL,
        actor_user_id INTEGER,
        created_at TEXT NOT NULL,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE RESTRICT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reservation_documents (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        organization_id INTEGER NOT NULL,
        reservation_id INTEGER NOT NULL,
        doc_type TEXT NOT NULL,
        original_filename TEXT NOT NULL,
        stored_name TEXT NOT NULL,
        content_type TEXT,
        size_bytes INTEGER,
        uploaded_by_user_id INTEGER,
        created_at TEXT NOT NULL,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE RESTRICT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reservation_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        organization_id INTEGER NOT NULL,
        reservation_id INTEGER NOT NULL,
        event_type TEXT NOT NULL,
        actor_user_id INTEGER,
        payload_json TEXT,
        created_at TEXT NOT NULL,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE RESTRICT
    )
    """,
)

POSTGRES_TABLES = (
    f"""
    CREATE TABLE IF NOT EXISTS reservations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        organization_id BIGINT NOT NULL,
        property_id BIGINT NOT NULL,
        contact_id BIGINT,
        agent_id BIGINT,
        visit_id BIGINT,
        operation_id BIGINT,
        reservation_status TEXT NOT NULL,
        original_property_price {_MONEY_PG},
        original_currency TEXT,
        agreed_property_price {_MONEY_PG},
        agreed_currency TEXT,
        reservation_amount {_MONEY_PG},
        reservation_currency TEXT,
        payment_method TEXT,
        next_milestone TEXT,
        estimated_closing_date TEXT,
        notes TEXT,
        reserved_at TEXT NOT NULL,
        price_decision TEXT,
        cancelled_by_user_id BIGINT,
        cancelled_at TEXT,
        created_by_user_id BIGINT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE RESTRICT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reservation_notes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        organization_id BIGINT NOT NULL,
        reservation_id BIGINT NOT NULL,
        body TEXT NOT NULL,
        actor_user_id BIGINT,
        created_at TEXT NOT NULL,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE RESTRICT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reservation_documents (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        organization_id BIGINT NOT NULL,
        reservation_id BIGINT NOT NULL,
        doc_type TEXT NOT NULL,
        original_filename TEXT NOT NULL,
        stored_name TEXT NOT NULL,
        content_type TEXT,
        size_bytes INTEGER,
        uploaded_by_user_id BIGINT,
        created_at TEXT NOT NULL,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE RESTRICT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reservation_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        organization_id BIGINT NOT NULL,
        reservation_id BIGINT NOT NULL,
        event_type TEXT NOT NULL,
        actor_user_id BIGINT,
        payload_json TEXT,
        created_at TEXT NOT NULL,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE RESTRICT
    )
    """,
)

OPEN_RESERVATION_INDEX = """
CREATE UNIQUE INDEX IF NOT EXISTS idx_reservations_one_open_property
ON reservations (organization_id, property_id)
WHERE reservation_status IN (
    'reserved', 'confirmed', 'documentation', 'financing',
    'contract', 'deed_scheduled', 'in_operation'
)
"""

INDEXES = (
    "CREATE INDEX IF NOT EXISTS idx_reservations_org_status ON reservations (organization_id, reservation_status)",
    "CREATE INDEX IF NOT EXISTS idx_reservations_org_agent ON reservations (organization_id, agent_id)",
    "CREATE INDEX IF NOT EXISTS idx_reservations_org_property ON reservations (organization_id, property_id)",
    "CREATE INDEX IF NOT EXISTS idx_reservations_confirmed_by ON reservations (organization_id, confirmed_by_user_id)",
    OPEN_RESERVATION_INDEX,
    "CREATE INDEX IF NOT EXISTS idx_reservation_notes_reservation ON reservation_notes (organization_id, reservation_id, id)",
    "CREATE INDEX IF NOT EXISTS idx_reservation_documents_reservation ON reservation_documents (organization_id, reservation_id)",
    "CREATE INDEX IF NOT EXISTS idx_reservation_documents_operation ON reservation_documents (organization_id, operation_id)",
    "CREATE INDEX IF NOT EXISTS idx_reservation_events_reservation ON reservation_events (organization_id, reservation_id, id)",
    "CREATE INDEX IF NOT EXISTS idx_reservation_deposits_org ON reservation_deposits (organization_id)",
    "CREATE INDEX IF NOT EXISTS idx_reservation_deposits_reservation ON reservation_deposits (organization_id, reservation_id)",
)


def _column_names(cursor, table, postgres):
    if postgres:
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = ?
            """,
            (table,),
        )
        return {row[0] for row in cursor.fetchall()}
    cursor.execute(f"PRAGMA table_info({table})")
    return {row[1] for row in cursor.fetchall()}


def _add_column(cursor, table, column, definition, postgres):
    if column in _column_names(cursor, table, postgres):
        return
    cursor.execute(f"ALTER TABLE {table} ADD COLUMN {definition}")


def _ensure_wizard_schema(cursor, postgres):
    money = _MONEY_PG if postgres else "REAL"
    user_id = "BIGINT" if postgres else "INTEGER"
    if postgres:
        cursor.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_name = 'users'"
        )
    else:
        cursor.execute(
            "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'users'"
        )
    user_fk = " REFERENCES users(id)" if cursor.fetchone() else ""
    reservation_columns = (
        ("is_shared_transaction", "is_shared_transaction INTEGER NOT NULL DEFAULT 0"),
        ("shared_brokerage_name", "shared_brokerage_name TEXT"),
        ("seller_commission_amount", f"seller_commission_amount {money}"),
        ("seller_commission_currency", "seller_commission_currency TEXT"),
        ("buyer_commission_amount", f"buyer_commission_amount {money}"),
        ("buyer_commission_currency", "buyer_commission_currency TEXT"),
        ("deposit_type", "deposit_type TEXT"),
        ("confirmed_at", "confirmed_at TEXT"),
        (
            "confirmed_by_user_id",
            f"confirmed_by_user_id {user_id}{user_fk}",
        ),
    )
    for column, definition in reservation_columns:
        _add_column(cursor, "reservations", column, definition, postgres)
    _add_column(
        cursor,
        "reservation_documents",
        "operation_id",
        f"operation_id {user_id}",
        postgres,
    )
    cursor.execute(
        """
        UPDATE reservations
        SET deposit_type = 'reservation'
        WHERE reservation_amount IS NOT NULL
            AND (deposit_type IS NULL OR deposit_type = '')
        """
    )
    if postgres:
        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS reservation_deposits (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                organization_id BIGINT NOT NULL,
                reservation_id BIGINT NOT NULL,
                deposit_type TEXT NOT NULL,
                amount {money} NOT NULL,
                currency TEXT NOT NULL,
                note TEXT,
                deposited_at TEXT,
                created_by_user_id BIGINT,
                created_at TEXT NOT NULL,
                FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
                FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE RESTRICT,
                FOREIGN KEY (created_by_user_id) REFERENCES users(id)
            )
            """
        )
    else:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS reservation_deposits (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                organization_id INTEGER NOT NULL,
                reservation_id INTEGER NOT NULL,
                deposit_type TEXT NOT NULL,
                amount REAL NOT NULL,
                currency TEXT NOT NULL,
                note TEXT,
                deposited_at TEXT,
                created_by_user_id INTEGER,
                created_at TEXT NOT NULL,
                FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
                FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE RESTRICT,
                FOREIGN KEY (created_by_user_id) REFERENCES users(id)
            )
            """
        )
    cursor.execute("DROP INDEX IF EXISTS idx_reservations_one_open_property")


def _apply(cursor, tables, postgres):
    for statement in tables:
        cursor.execute(statement)
    _ensure_wizard_schema(cursor, postgres)
    for statement in INDEXES:
        cursor.execute(statement)


def migrate_reservations_sqlite():
    connection = get_connection()
    try:
        cursor = connection.cursor()
        _apply(cursor, SQLITE_TABLES, postgres=False)
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def migrate_reservations_postgres(cursor):
    _apply(cursor, POSTGRES_TABLES, postgres=True)


def migrate_reservations():
    if get_database_backend() == BACKEND_POSTGRES:
        connection = get_connection()
        try:
            cursor = connection.cursor()
            migrate_reservations_postgres(cursor)
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()
        return
    migrate_reservations_sqlite()
