"""
Clean PostgreSQL schema for the current final application model.

This is NOT a port of SQLite migrate_schema() history (no PRAGMA,
no table rebuilds). Apply once via create_postgres_schema().

Type policy (Phase 2):
- IDs: BIGINT GENERATED BY DEFAULT AS IDENTITY
- Money / rates / percents: NUMERIC(18,4) — no 2-decimal truncation in DB
- Flags (is_active, is_read, registration_enabled): SMALLINT 0/1
  to match existing repository writes (`1 if flag else 0`) and
  predicates (`= 0` / `= 1`) without conversion layers
- Timestamps and operation_date: TEXT (ISO / DD/MM/YYYY) for
  compatibility; operation_date is NOT migrated to DATE yet
"""

from __future__ import annotations

from modules.database.connection import get_connection


POSTGRES_SCHEMA_VERSION = "postgres_v18"

# Money / calculation columns use NUMERIC(18,4).
_MONEY = "NUMERIC(18, 4)"
_ID = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
_FLAG = "SMALLINT"


SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS schema_migrations (
        version TEXT PRIMARY KEY,
        applied_at TEXT NOT NULL
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS organizations (
        id {_ID},
        name TEXT NOT NULL,
        is_active {_FLAG} NOT NULL DEFAULT 1
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS organization_settings (
        organization_id BIGINT PRIMARY KEY,
        display_name TEXT NOT NULL,
        default_language TEXT NOT NULL DEFAULT 'es',
        default_currency TEXT NOT NULL DEFAULT 'USD',
        timezone TEXT NOT NULL
            DEFAULT 'America/Argentina/Buenos_Aires',
        logo_path TEXT,
        accent_color TEXT,
        registration_code_hash TEXT,
        registration_enabled {_FLAG} NOT NULL DEFAULT 1,
        registration_code_rotated_at TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE CASCADE
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS agents (
        id {_ID},
        name TEXT NOT NULL,
        type TEXT NOT NULL,
        organization_id BIGINT NOT NULL,
        external_provider TEXT,
        external_id TEXT,
        last_synced_at TEXT,
        team_leader_agent_id BIGINT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (team_leader_agent_id)
            REFERENCES agents(id)
            ON DELETE SET NULL
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agents_team_leader
    ON agents (organization_id, team_leader_agent_id)
    WHERE team_leader_agent_id IS NOT NULL
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_agents_org_external_identity
    ON agents (
        organization_id,
        external_provider,
        external_id
    )
    WHERE external_provider IS NOT NULL
        AND external_id IS NOT NULL
        AND external_id <> ''
    """,
    f"""
    CREATE TABLE IF NOT EXISTS properties (
        id {_ID},
        address TEXT NOT NULL,
        jurisdiction TEXT NOT NULL,
        organization_id BIGINT NOT NULL,
        agent_id BIGINT,
        property_type TEXT,
        listing_price {_MONEY},
        listing_purpose TEXT,
        listing_currency TEXT,
        neighborhood TEXT,
        rooms INTEGER,
        bedrooms INTEGER,
        bathrooms INTEGER,
        covered_m2 {_MONEY},
        total_m2 {_MONEY},
        parking_spaces INTEGER,
        description TEXT,
        commercial_status TEXT,
        features_json TEXT,
        last_synced_at TEXT,
        external_id TEXT,
        status TEXT NOT NULL DEFAULT 'approved',
        rejection_reason TEXT,
        reviewed_by_user_id BIGINT,
        reviewed_at TEXT,
        created_by_user_id BIGINT,
        submitted_at TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE RESTRICT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS operations (
        id {_ID},
        operation_date TEXT NOT NULL,
        agent_id BIGINT NOT NULL,
        property_id BIGINT NOT NULL,
        organization_id BIGINT NOT NULL,
        was_invoiced TEXT NOT NULL,
        invoice_full_commission TEXT NOT NULL DEFAULT 'no',
        vat_amount {_MONEY} NOT NULL,
        sale_price {_MONEY} NOT NULL,
        commission_rate {_MONEY} NOT NULL,
        total_commission {_MONEY} NOT NULL,
        commission_after_abao {_MONEY} NOT NULL,
        abao {_MONEY} NOT NULL,
        martillero {_MONEY} NOT NULL,
        agent_payment {_MONEY} NOT NULL,
        office_payment {_MONEY} NOT NULL,
        office_total {_MONEY} NOT NULL,
        currency TEXT NOT NULL DEFAULT 'USD',
        original_amount {_MONEY},
        exchange_rate {_MONEY} NOT NULL DEFAULT 1,
        status TEXT NOT NULL DEFAULT 'approved',
        rejection_reason TEXT,
        created_by_user_id BIGINT,
        reviewed_by_user_id BIGINT,
        reviewed_at TEXT,

        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (property_id)
            REFERENCES properties(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS users (
        id {_ID},
        username TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL,
        agent_id BIGINT,
        is_active {_FLAG} NOT NULL DEFAULT 1,
        organization_id BIGINT NOT NULL,
        email TEXT,
        first_name TEXT,
        last_name TEXT,
        phone TEXT,
        account_status TEXT NOT NULL DEFAULT 'active',

        UNIQUE (organization_id, username),

        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE SET NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS registration_requests (
        id {_ID},
        organization_id BIGINT NOT NULL,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT NOT NULL,
        phone TEXT,
        password_hash TEXT NOT NULL,
        status TEXT NOT NULL,
        rejection_reason TEXT,
        reviewed_by_user_id BIGINT,
        reviewed_at TEXT,
        created_at TEXT NOT NULL,
        email_verified_at TEXT,
        approved_user_id BIGINT,
        approved_agent_id BIGINT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS email_verification_tokens (
        id {_ID},
        registration_request_id BIGINT NOT NULL,
        token_hash TEXT NOT NULL,
        expires_at TEXT NOT NULL,
        used_at TEXT,
        created_at TEXT NOT NULL,
        attempt_count INTEGER NOT NULL DEFAULT 0,
        invalidated_at TEXT,
        last_sent_at TEXT,

        FOREIGN KEY (registration_request_id)
            REFERENCES registration_requests(id)
            ON DELETE CASCADE
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS organization_guest_access (
        id {_ID},
        organization_id BIGINT NOT NULL,
        token_hash TEXT NOT NULL UNIQUE,
        label TEXT,
        created_by_user_id BIGINT,
        created_at TEXT NOT NULL,
        expires_at TEXT,
        revoked_at TEXT,
        last_used_at TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE CASCADE
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS notifications (
        id {_ID},
        organization_id BIGINT NOT NULL,
        user_id BIGINT NOT NULL,
        kind TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        entity_id BIGINT NOT NULL,
        payload_json TEXT,
        is_read {_FLAG} NOT NULL DEFAULT 0,
        actor_user_id BIGINT,
        created_at TEXT NOT NULL,
        event_key TEXT,
        read_at TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS operation_documents (
        id {_ID},
        organization_id BIGINT NOT NULL,
        operation_id BIGINT,
        doc_type TEXT NOT NULL,
        stored_name TEXT NOT NULL,
        original_filename TEXT NOT NULL,
        content_type TEXT NOT NULL,
        size_bytes INTEGER NOT NULL,
        uploaded_by_user_id BIGINT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (operation_id)
            REFERENCES operations(id)
            ON DELETE CASCADE,

        FOREIGN KEY (uploaded_by_user_id)
            REFERENCES users(id)
            ON DELETE RESTRICT,

        CHECK (
            doc_type IN (
                'martillero_client',
                'agent_client',
                'uif_form',
                'uif_additional',
                'transfer_receipt',
                'reservation_deposit',
                'deed_contract',
                'other'
            )
        )
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_operation_documents_structured_unique
    ON operation_documents (
        organization_id,
        operation_id,
        doc_type
    )
    WHERE doc_type <> 'other'
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_operation_documents_org_operation
    ON operation_documents (
        organization_id,
        operation_id
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_operation_documents_operation
    ON operation_documents (operation_id)
    """,
    f"""
    CREATE TABLE IF NOT EXISTS property_change_requests (
        id {_ID},
        organization_id BIGINT NOT NULL,
        property_id BIGINT NOT NULL,
        requested_by_user_id BIGINT NOT NULL,
        proposed_address TEXT NOT NULL,
        proposed_jurisdiction TEXT NOT NULL,
        proposed_agent_id BIGINT,
        status TEXT NOT NULL,
        rejection_reason TEXT,
        reviewed_by_user_id BIGINT,
        reviewed_at TEXT,
        created_at TEXT NOT NULL,
        proposed_property_type TEXT,
        proposed_listing_price {_MONEY},
        proposed_listing_purpose TEXT,
        proposed_listing_currency TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (property_id)
            REFERENCES properties(id)
            ON DELETE RESTRICT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS property_external_listings (
        id {_ID},
        organization_id BIGINT NOT NULL,
        property_id BIGINT NOT NULL,
        provider TEXT NOT NULL,
        provider_label TEXT,
        external_id TEXT,
        url TEXT,
        status TEXT NOT NULL,
        listing_currency TEXT,
        buyer_side_commission_percent {_MONEY},
        seller_side_commission_percent {_MONEY},
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        last_synced_at TEXT,
        created_by_user_id BIGINT,
        updated_by_user_id BIGINT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (property_id)
            REFERENCES properties(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,

        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,

        CHECK (
            provider IN (
                'remax_web',
                'organization_website',
                'zonaprop',
                'argenprop',
                'mercadolibre',
                'other'
            )
        ),
        CHECK (
            status IN (
                'active',
                'paused',
                'reserved',
                'negotiation',
                'sold',
                'inactive'
            )
        ),
        CHECK (
            listing_currency IS NULL
            OR listing_currency IN ('USD', 'ARS')
        ),
        CHECK (
            url IS NULL
            OR url LIKE 'http://%'
            OR url LIKE 'https://%'
        )
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_property_external_listings_org_property
    ON property_external_listings (
        organization_id,
        property_id
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_property_external_listings_org_provider
    ON property_external_listings (
        organization_id,
        provider
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_property_external_listings_structured_provider
    ON property_external_listings (
        organization_id,
        property_id,
        provider
    )
    WHERE provider <> 'other'
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_property_external_listings_external_id
    ON property_external_listings (
        organization_id,
        provider,
        external_id
    )
    WHERE external_id IS NOT NULL
        AND external_id <> ''
    """,
    f"""
    CREATE TABLE IF NOT EXISTS organization_integrations (
        id {_ID},
        organization_id BIGINT NOT NULL,
        provider TEXT NOT NULL,
        scope_type TEXT NOT NULL,
        agent_id BIGINT,
        status TEXT NOT NULL DEFAULT 'disconnected',
        external_office_id TEXT,
        config_json TEXT,
        last_synced_at TEXT,
        last_sync_status TEXT,
        last_sync_error TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE RESTRICT,

        CHECK (
            provider IN (
                'remax',
                'organization_website',
                'stub_fixture',
                'csv_upload'
            )
        ),
        CHECK (
            scope_type IN ('organization', 'agent')
        ),
        CHECK (
            status IN (
                'disconnected',
                'connected',
                'error',
                'disabled'
            )
        ),
        CHECK (
            last_sync_status IS NULL
            OR last_sync_status IN ('ok', 'partial', 'failed')
        ),
        CHECK (
            (
                scope_type = 'organization'
                AND agent_id IS NULL
            )
            OR (
                scope_type = 'agent'
                AND agent_id IS NOT NULL
            )
        )
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_org_integrations_org_provider_org_scope
    ON organization_integrations (
        organization_id,
        provider
    )
    WHERE scope_type = 'organization'
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_org_integrations_org_provider_agent_scope
    ON organization_integrations (
        organization_id,
        provider,
        agent_id
    )
    WHERE scope_type = 'agent'
        AND agent_id IS NOT NULL
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_org_integrations_organization
    ON organization_integrations (organization_id)
    """,
    """
    CREATE TABLE IF NOT EXISTS csv_import_batches (
        id TEXT PRIMARY KEY,
        organization_id BIGINT NOT NULL,
        filename TEXT,
        payload_json TEXT NOT NULL,
        preview_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        expires_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE CASCADE
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_csv_import_batches_organization
    ON csv_import_batches (organization_id)
    """,
    f"""
    CREATE TABLE IF NOT EXISTS integration_sync_runs (
        id {_ID},
        organization_id BIGINT NOT NULL,
        integration_id BIGINT NOT NULL,
        started_at TEXT NOT NULL,
        finished_at TEXT,
        status TEXT NOT NULL,
        agents_created INTEGER NOT NULL DEFAULT 0,
        agents_updated INTEGER NOT NULL DEFAULT 0,
        properties_created INTEGER NOT NULL DEFAULT 0,
        properties_updated INTEGER NOT NULL DEFAULT 0,
        listings_created INTEGER NOT NULL DEFAULT 0,
        listings_updated INTEGER NOT NULL DEFAULT 0,
        listings_deactivated INTEGER NOT NULL DEFAULT 0,
        error_summary TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (integration_id)
            REFERENCES organization_integrations(id)
            ON DELETE CASCADE,

        CHECK (
            status IN ('running', 'ok', 'partial', 'failed')
        )
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_integration_sync_runs_integration
    ON integration_sync_runs (
        integration_id,
        started_at
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS agent_wallet_movements (
        id {_ID},
        organization_id BIGINT NOT NULL,
        agent_id BIGINT NOT NULL,
        operation_id BIGINT,
        movement_type TEXT NOT NULL,
        amount {_MONEY} NOT NULL,
        currency TEXT NOT NULL DEFAULT 'USD',
        source_agent_id BIGINT,
        related_movement_id BIGINT,
        description TEXT,
        reference TEXT,
        idempotency_key TEXT,
        created_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (operation_id)
            REFERENCES operations(id)
            ON DELETE SET NULL,

        FOREIGN KEY (source_agent_id)
            REFERENCES agents(id)
            ON DELETE SET NULL,

        FOREIGN KEY (related_movement_id)
            REFERENCES agent_wallet_movements(id)
            ON DELETE SET NULL,

        CHECK (
            movement_type IN (
                'own_commission',
                'team_leader_income',
                'adjustment',
                'reversal'
            )
        ),
        CHECK (currency IN ('USD', 'ARS'))
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS idx_wallet_idempotency
    ON agent_wallet_movements (
        organization_id,
        idempotency_key
    )
    WHERE idempotency_key IS NOT NULL
        AND idempotency_key <> ''
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_wallet_agent
    ON agent_wallet_movements (
        organization_id,
        agent_id,
        created_at
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_wallet_operation
    ON agent_wallet_movements (
        organization_id,
        operation_id
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS agent_account_movements (
        id {_ID},
        organization_id BIGINT NOT NULL,
        agent_id BIGINT NOT NULL,
        movement_type TEXT NOT NULL,
        currency TEXT NOT NULL,
        amount {_MONEY} NOT NULL,
        description TEXT NOT NULL,
        balance_before {_MONEY} NOT NULL,
        balance_after {_MONEY} NOT NULL,
        status TEXT NOT NULL DEFAULT 'confirmed',
        source_type TEXT NOT NULL DEFAULT 'manual',
        source_id BIGINT,
        movement_date TEXT NOT NULL,
        idempotency_key TEXT,
        created_by_user_id BIGINT,
        created_at TEXT NOT NULL,
        reversed_movement_id BIGINT,
        reversal_reason TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,

        FOREIGN KEY (reversed_movement_id)
            REFERENCES agent_account_movements(id)
            ON DELETE SET NULL,

        CHECK (
            movement_type IN (
                'charge',
                'credit',
                'payment',
                'fee',
                'commission',
                'adjustment'
            )
        ),
        CHECK (currency IN ('USD', 'ARS')),
        CHECK (amount > 0),
        CHECK (status IN ('confirmed', 'reversed')),
        CHECK (
            source_type IN (
                'manual',
                'invoice',
                'cash',
                'operation',
                'fee',
                'commission',
                'system',
                'recurring_charge'
            )
        )
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_agent_account_org_agent_currency
    ON agent_account_movements (
        organization_id,
        agent_id,
        currency,
        movement_date,
        id
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_agent_account_org_date
    ON agent_account_movements (
        organization_id,
        movement_date,
        id
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_agent_account_idempotency
    ON agent_account_movements (
        organization_id,
        idempotency_key
    )
    WHERE idempotency_key IS NOT NULL
        AND idempotency_key <> ''
    """,
    f"""
    CREATE TABLE IF NOT EXISTS agent_recurring_charges (
        id {_ID},
        organization_id BIGINT NOT NULL,
        agent_id BIGINT NOT NULL,
        charge_category TEXT NOT NULL,
        description TEXT,
        currency TEXT NOT NULL,
        input_amount {_MONEY} NOT NULL,
        vat_mode TEXT NOT NULL,
        net_amount {_MONEY} NOT NULL,
        vat_rate {_MONEY} NOT NULL,
        vat_amount {_MONEY} NOT NULL,
        gross_amount {_MONEY} NOT NULL,
        recurrence_type TEXT NOT NULL,
        billing_day INTEGER,
        start_date TEXT NOT NULL,
        end_date TEXT,
        next_run_date TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        created_by_user_id BIGINT,
        created_at TEXT NOT NULL,
        updated_by_user_id BIGINT,
        updated_at TEXT NOT NULL,
        last_generated_at TEXT,
        paused_at TEXT,
        paused_by_user_id BIGINT,
        ended_at TEXT,
        ended_by_user_id BIGINT,
        FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (agent_id)
            REFERENCES agents(id) ON DELETE RESTRICT,
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (paused_by_user_id)
            REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (ended_by_user_id)
            REFERENCES users(id) ON DELETE SET NULL,
        CHECK (currency IN ('USD', 'ARS')),
        CHECK (vat_mode IN ('none', 'add_vat', 'gross_includes_vat')),
        CHECK (recurrence_type IN ('monthly', 'annual')),
        CHECK (status IN ('active', 'paused', 'ended')),
        CHECK (input_amount > 0),
        CHECK (gross_amount > 0),
        CHECK (
            (recurrence_type = 'monthly' AND billing_day BETWEEN 1 AND 28)
            OR recurrence_type = 'annual'
        )
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS agent_tasks (
        id {_ID},
        organization_id BIGINT NOT NULL,
        agent_id BIGINT NOT NULL,
        title TEXT NOT NULL,
        description TEXT,
        task_type TEXT NOT NULL,
        due_at TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending',
        priority TEXT NOT NULL DEFAULT 'normal',
        property_id BIGINT,
        operation_id BIGINT,
        related_entity_type TEXT,
        related_entity_id BIGINT,
        contact_name TEXT,
        duration_minutes INTEGER,
        reminder_minutes INTEGER,
        attendance_status TEXT,
        outcome_json TEXT,
        google_event_id TEXT,
        created_by_user_id BIGINT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        completed_at TEXT,
        completed_by_user_id BIGINT,
        cancelled_at TEXT,
        cancelled_by_user_id BIGINT,
        FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (agent_id)
            REFERENCES agents(id) ON DELETE RESTRICT,
        FOREIGN KEY (property_id)
            REFERENCES properties(id) ON DELETE SET NULL,
        FOREIGN KEY (operation_id)
            REFERENCES operations(id) ON DELETE SET NULL,
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (completed_by_user_id)
            REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (cancelled_by_user_id)
            REFERENCES users(id) ON DELETE SET NULL,
        CHECK (status IN ('pending', 'completed', 'cancelled')),
        CHECK (priority IN ('normal', 'high')),
        CHECK (task_type IN (
            'call',
            'visit',
            'meeting',
            'follow_up',
            'documentation',
            'valuation',
            'reminder',
            'other'
        ))
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_tasks_agent_due
    ON agent_tasks (organization_id, agent_id, status, due_at)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_tasks_org_due
    ON agent_tasks (organization_id, status, due_at)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_tasks_property
    ON agent_tasks (organization_id, property_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_tasks_operation
    ON agent_tasks (organization_id, operation_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_tasks_related
    ON agent_tasks (
        organization_id,
        related_entity_type,
        related_entity_id
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_tasks_google_event
    ON agent_tasks (organization_id, google_event_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_tasks_contact
    ON agent_tasks (organization_id, contact_id)
    """,
    f"""
    CREATE TABLE IF NOT EXISTS contacts (
        id {_ID},
        organization_id BIGINT NOT NULL,
        agent_id BIGINT NOT NULL,
        name TEXT NOT NULL,
        phone TEXT,
        email TEXT,
        status TEXT NOT NULL DEFAULT 'lead',
        source TEXT NOT NULL DEFAULT 'manual',
        visibility TEXT NOT NULL DEFAULT 'private',
        notes TEXT,
        preferences_json TEXT,
        last_interacted_at TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (agent_id)
            REFERENCES agents(id) ON DELETE RESTRICT,
        CHECK (status IN ('lead', 'active', 'inactive', 'closed')),
        CHECK (source IN ('manual', 'whatsapp', 'agenda', 'operation', 'other')),
        CHECK (visibility IN ('private', 'team', 'organization'))
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_contacts_owner
    ON contacts (organization_id, agent_id, status, updated_at)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_contacts_org_visibility
    ON contacts (organization_id, visibility, agent_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_contacts_org_name
    ON contacts (organization_id, name)
    """,
    f"""
    CREATE TABLE IF NOT EXISTS google_calendar_connections (
        id {_ID},
        organization_id BIGINT NOT NULL,
        user_id BIGINT NOT NULL,
        google_email TEXT,
        calendar_id TEXT NOT NULL DEFAULT 'primary',
        refresh_token_encrypted TEXT NOT NULL,
        access_token_encrypted TEXT,
        access_expires_at TEXT,
        sync_token TEXT,
        status TEXT NOT NULL DEFAULT 'active',
        last_synced_at TEXT,
        last_error TEXT,
        events_cache_json TEXT,
        connected_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE RESTRICT,
        FOREIGN KEY (user_id)
            REFERENCES users(id) ON DELETE CASCADE,
        CHECK (status IN ('active', 'error', 'revoked'))
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS idx_google_calendar_user
    ON google_calendar_connections (organization_id, user_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_recurring_org_agent
    ON agent_recurring_charges (
        organization_id, agent_id, status, next_run_date, id
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agent_recurring_due
    ON agent_recurring_charges (
        organization_id, status, next_run_date, id
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS idx_aa_recurring_charge_period
    ON agent_account_movements (
        organization_id, source_id, billing_period
    )
    WHERE movement_type = 'charge'
        AND source_type = 'recurring_charge'
        AND source_id IS NOT NULL
        AND billing_period IS NOT NULL
    """,
    f"""
    CREATE TABLE IF NOT EXISTS cash_accounts (
        id {_ID},
        organization_id BIGINT NOT NULL,
        currency TEXT NOT NULL,
        cached_balance {_MONEY} NOT NULL DEFAULT 0,
        updated_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        CHECK (currency IN ('USD', 'ARS')),
        UNIQUE (organization_id, currency)
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS treasury_accounts (
        id {_ID},
        organization_id BIGINT NOT NULL,
        name TEXT NOT NULL,
        account_type TEXT NOT NULL,
        currency TEXT NOT NULL,
        bank_name TEXT,
        account_reference TEXT,
        is_default {_FLAG} NOT NULL DEFAULT 0,
        is_active {_FLAG} NOT NULL DEFAULT 1,
        cached_balance {_MONEY} NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL,
        created_by_user_id BIGINT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,

        CHECK (
            account_type IN (
                'cash',
                'bank',
                'digital_wallet',
                'other'
            )
        ),
        CHECK (currency IN ('USD', 'ARS'))
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_treasury_accounts_org_currency
        ON treasury_accounts (
            organization_id,
            currency,
            is_active
        )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS cash_movements (
        id {_ID},
        organization_id BIGINT NOT NULL,
        movement_number INTEGER NOT NULL,
        movement_type TEXT NOT NULL,
        currency TEXT NOT NULL,
        amount {_MONEY} NOT NULL,
        category TEXT NOT NULL,
        description TEXT NOT NULL,
        payment_method TEXT NOT NULL,
        movement_date TEXT NOT NULL,
        created_at TEXT NOT NULL,
        created_by_user_id BIGINT,
        updated_at TEXT,
        updated_by_user_id BIGINT,
        status TEXT NOT NULL DEFAULT 'confirmed',
        notes TEXT,
        attachment_path TEXT,
        source TEXT NOT NULL DEFAULT 'manual',
        source_reference TEXT,
        reversal_of_movement_id BIGINT,
        reversal_reason TEXT,
        balance_before {_MONEY} NOT NULL,
        balance_after {_MONEY} NOT NULL,
        merchant TEXT,
        receipt_number TEXT,
        attachment_hash TEXT,
        attachment_content_type TEXT,
        attachment_original_name TEXT,
        treasury_account_id BIGINT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,
        FOREIGN KEY (reversal_of_movement_id)
            REFERENCES cash_movements(id)
            ON DELETE SET NULL,
        FOREIGN KEY (treasury_account_id)
            REFERENCES treasury_accounts(id)
            ON DELETE SET NULL,

        CHECK (
            movement_type IN (
                'income',
                'expense',
                'adjustment',
                'opening_balance',
                'reversal'
            )
        ),
        CHECK (currency IN ('USD', 'ARS')),
        CHECK (amount > 0),
        CHECK (status IN ('confirmed', 'reversed')),
        UNIQUE (organization_id, movement_number)
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_cash_movements_org_date
    ON cash_movements (
        organization_id,
        movement_date,
        id
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_cash_movements_org_currency
        ON cash_movements (
            organization_id,
            currency,
            status
        )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_cash_accounts_org
        ON cash_accounts (organization_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_cash_movements_attachment_hash
    ON cash_movements (
        organization_id,
        attachment_hash
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS cash_ai_drafts (
        id {_ID},
        organization_id BIGINT NOT NULL,
        created_by_user_id BIGINT,
        status TEXT NOT NULL DEFAULT 'processing',
        user_context_text TEXT,
        attachment_path TEXT,
        attachment_hash TEXT,
        attachment_content_type TEXT,
        attachment_original_name TEXT,
        confirm_token TEXT NOT NULL,
        confirmed_movement_id BIGINT,
        error_message_key TEXT,
        confidence TEXT,
        provider TEXT,
        draft_json TEXT,
        fields_needing_review_json TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,
        FOREIGN KEY (confirmed_movement_id)
            REFERENCES cash_movements(id)
            ON DELETE SET NULL,

        CHECK (
            status IN (
                'processing',
                'review',
                'confirmed',
                'failed',
                'discarded'
            )
        ),
        UNIQUE (organization_id, confirm_token)
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_cash_ai_drafts_org_status
    ON cash_ai_drafts (
        organization_id,
        status,
        id
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS agent_billing_profiles (
        id {_ID},
        organization_id BIGINT NOT NULL,
        agent_id BIGINT NOT NULL,
        legal_name TEXT NOT NULL,
        tax_id TEXT NOT NULL,
        tax_condition TEXT NOT NULL,
        fiscal_address TEXT NOT NULL,
        email TEXT,
        point_of_sale TEXT,
        allowed_invoice_types TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,
        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE CASCADE,

        UNIQUE (organization_id, agent_id)
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_agent_billing_profiles_org
    ON agent_billing_profiles (organization_id)
    """,
    f"""
    CREATE TABLE IF NOT EXISTS billing_issuer_profiles (
        id {_ID},
        organization_id BIGINT NOT NULL,
        issuer_type TEXT NOT NULL,
        display_name TEXT NOT NULL,
        legal_name TEXT NOT NULL,
        tax_id TEXT NOT NULL,
        tax_condition TEXT,
        fiscal_address TEXT,
        email TEXT,
        is_default {_FLAG} NOT NULL DEFAULT 0,
        is_active {_FLAG} NOT NULL DEFAULT 1,
        point_of_sale TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        deactivated_at TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        CHECK (
            issuer_type IN (
                'organization',
                'broker',
                'other'
            )
        )
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_billing_issuer_profiles_org_active
    ON billing_issuer_profiles (
        organization_id,
        is_active
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS operation_parties (
        id {_ID},
        organization_id BIGINT NOT NULL,
        operation_id BIGINT NOT NULL,
        party_role TEXT NOT NULL,
        is_participating {_FLAG} NOT NULL DEFAULT 1,
        commission_percent {_MONEY},
        commission_amount {_MONEY},
        client_legal_name TEXT,
        client_tax_id TEXT,
        client_tax_condition TEXT,
        client_fiscal_address TEXT,
        client_email TEXT,
        client_phone TEXT,
        invoice_amount {_MONEY},
        invoice_currency TEXT,
        invoice_exchange_rate {_MONEY},
        invoice_amount_set_at TEXT,
        invoice_amount_set_by_user_id BIGINT,
        billing_enabled {_FLAG} NOT NULL DEFAULT 0,
        billing_enabled_at TEXT,
        billing_enabled_by_user_id BIGINT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,
        FOREIGN KEY (operation_id)
            REFERENCES operations(id)
            ON DELETE RESTRICT,

        CHECK (
            party_role IN ('buyer', 'seller')
        ),
        UNIQUE (
            organization_id,
            operation_id,
            party_role
        )
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_operation_parties_org_op
    ON operation_parties (
        organization_id,
        operation_id
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_operation_parties_org_billing
    ON operation_parties (
        organization_id,
        billing_enabled
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS invoices (
        id {_ID},
        organization_id BIGINT NOT NULL,
        invoice_seq INTEGER NOT NULL,
        invoice_number_internal TEXT NOT NULL,
        operation_id BIGINT NOT NULL,
        agent_id BIGINT NOT NULL,
        issuer_user_id BIGINT,
        issuer_type TEXT NOT NULL,
        issuer_name TEXT NOT NULL,
        issuer_tax_id TEXT NOT NULL,
        issuer_tax_condition TEXT,
        issuer_address TEXT,
        recipient_name TEXT NOT NULL,
        recipient_tax_id TEXT NOT NULL,
        recipient_tax_condition TEXT,
        recipient_address TEXT,
        invoice_type TEXT NOT NULL DEFAULT 'internal',
        service_type TEXT NOT NULL DEFAULT 'services',
        description TEXT NOT NULL,
        quantity {_MONEY} NOT NULL DEFAULT 1,
        unit_price {_MONEY} NOT NULL,
        subtotal {_MONEY} NOT NULL,
        vat_amount {_MONEY} NOT NULL DEFAULT 0,
        total_amount {_MONEY} NOT NULL,
        currency TEXT NOT NULL DEFAULT 'ARS',
        exchange_rate {_MONEY},
        payment_condition TEXT NOT NULL,
        issue_date TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'draft',
        source TEXT NOT NULL DEFAULT 'agent_operation',
        external_invoice_number TEXT,
        point_of_sale TEXT,
        cae TEXT,
        cae_expiration TEXT,
        provider TEXT NOT NULL DEFAULT 'internal',
        provider_reference TEXT,
        pdf_path TEXT,
        created_at TEXT NOT NULL,
        created_by_user_id BIGINT,
        confirmed_at TEXT,
        confirmed_by_user_id BIGINT,
        updated_at TEXT NOT NULL,
        cancelled_at TEXT,
        cancelled_by_user_id BIGINT,
        cancellation_reason TEXT,
        cash_movement_id BIGINT,
        side TEXT,
        issuer_profile_id BIGINT,
        issuer_key TEXT,
        recipient_party_id BIGINT,
        origin_type TEXT NOT NULL DEFAULT 'operation',
        agent_account_movement_id BIGINT,
        invoice_purpose TEXT NOT NULL DEFAULT 'standard',
        charge_linked_at TEXT,
        charge_linked_by_user_id BIGINT,
        vat_rate {_MONEY} NOT NULL DEFAULT 0,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,
        FOREIGN KEY (operation_id)
            REFERENCES operations(id)
            ON DELETE RESTRICT,
        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE RESTRICT,
        FOREIGN KEY (issuer_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,
        FOREIGN KEY (confirmed_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,
        FOREIGN KEY (cancelled_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,
        CONSTRAINT fk_invoices_agent_account_movement
        FOREIGN KEY (agent_account_movement_id)
            REFERENCES agent_account_movements(id)
            ON DELETE RESTRICT,
        CONSTRAINT fk_invoices_charge_linked_user
        FOREIGN KEY (charge_linked_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,

        CHECK (
            status IN (
                'draft',
                'ready_to_issue',
                'issued',
                'error',
                'cancelled'
            )
        ),
        CHECK (
            payment_condition IN (
                'contado',
                'cuenta_corriente'
            )
        ),
        CHECK (
            issuer_type IN ('agent', 'admin')
        ),
        CONSTRAINT ck_invoices_origin_relation CHECK (
            (
                origin_type = 'operation'
                AND operation_id IS NOT NULL
            )
            OR (
                origin_type = 'agent_account_charge'
                AND agent_account_movement_id IS NOT NULL
            )
        ),
        CONSTRAINT ck_invoices_origin_type CHECK (
            origin_type IN (
                'operation',
                'agent_account_charge'
            )
        ),
        CHECK (quantity > 0),
        CHECK (total_amount > 0),
        UNIQUE (organization_id, invoice_seq),
        UNIQUE (
            organization_id,
            invoice_number_internal
        )
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_invoices_org_status
    ON invoices (
        organization_id,
        status,
        id
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_invoices_org_agent
    ON invoices (
        organization_id,
        agent_id,
        id
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_invoices_org_issue_date
    ON invoices (
        organization_id,
        issue_date,
        id
    )
    """,
)


POSTGRES_TABLES = (
    "schema_migrations",
    "organizations",
    "organization_settings",
    "agents",
    "properties",
    "operations",
    "users",
    "registration_requests",
    "email_verification_tokens",
    "organization_guest_access",
    "notifications",
    "operation_documents",
    "property_change_requests",
    "property_external_listings",
    "organization_integrations",
    "csv_import_batches",
    "integration_sync_runs",
    "agent_wallet_movements",
    "agent_account_movements",
    "cash_accounts",
    "cash_movements",
    "cash_ai_drafts",
    "agent_payment_ai_drafts",
    "agent_billing_profiles",
    "billing_issuer_profiles",
    "operation_parties",
    "invoices",
    "contacts",
)


def _schema_version_applied(cursor, version):
    cursor.execute(
        """
        SELECT 1
        FROM schema_migrations
        WHERE version = ?
        """,
        (version,),
    )
    return cursor.fetchone() is not None


def _record_schema_version(cursor, version):
    from datetime import datetime

    applied_at = datetime.utcnow().replace(
        microsecond=0
    ).isoformat()

    cursor.execute(
        """
        INSERT INTO schema_migrations (
            version,
            applied_at
        )
        VALUES (?, ?)
        ON CONFLICT (version) DO NOTHING
        """,
        (version, applied_at),
    )


def create_postgres_schema():
    """
    Idempotently create the PostgreSQL application schema.

    Safe to run repeatedly. Does not run SQLite migrations.
    """
    connection = get_connection()
    cursor = connection.cursor()

    try:
        for statement in SCHEMA_STATEMENTS:
            cursor.execute(statement)

        for column_name, column_sql in (
            ("event_key", "TEXT"),
            ("read_at", "TEXT"),
        ):
            cursor.execute(
                f"""
                ALTER TABLE notifications
                ADD COLUMN IF NOT EXISTS {column_name} {column_sql}
                """
            )

        cursor.execute(
            """
            UPDATE notifications
            SET read_at = created_at
            WHERE is_read = 1
                AND (read_at IS NULL OR read_at = '')
            """
        )

        cursor.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS
            idx_notifications_event_key
            ON notifications (
                organization_id,
                event_key
            )
            WHERE event_key IS NOT NULL
                AND event_key <> ''
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
            ON notifications (
                organization_id,
                user_id,
                is_read,
                id
            )
            """
        )

        cursor.execute(
            """
            DO $$
            DECLARE constraint_row RECORD;
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'agent_account_movements'::regclass
                        AND contype = 'c'
                        AND pg_get_constraintdef(oid)
                            ILIKE '%source_type%'
                        AND pg_get_constraintdef(oid)
                            ILIKE '%recurring_charge%'
                ) THEN
                    FOR constraint_row IN
                        SELECT conname
                        FROM pg_constraint
                        WHERE conrelid
                            = 'agent_account_movements'::regclass
                            AND contype = 'c'
                            AND pg_get_constraintdef(oid)
                                ILIKE '%source_type%'
                    LOOP
                        EXECUTE format(
                            'ALTER TABLE agent_account_movements '
                            'DROP CONSTRAINT %I',
                            constraint_row.conname
                        );
                    END LOOP;
                    ALTER TABLE agent_account_movements
                    ADD CONSTRAINT ck_agent_account_source_type
                    CHECK (
                        source_type IN (
                            'manual', 'invoice', 'cash', 'operation',
                            'fee', 'commission', 'system',
                            'recurring_charge'
                        )
                    );
                END IF;
            END
            $$;
            """
        )

        cursor.execute(
            """
            ALTER TABLE properties
            ADD COLUMN IF NOT EXISTS external_id TEXT
            """
        )

        cursor.execute(
            """
            UPDATE properties
            SET external_id = (
                SELECT pel.external_id
                FROM property_external_listings AS pel
                WHERE pel.property_id = properties.id
                    AND pel.organization_id
                        = properties.organization_id
                    AND pel.external_id IS NOT NULL
                    AND BTRIM(pel.external_id) <> ''
                ORDER BY pel.id
                LIMIT 1
            )
            WHERE external_id IS NULL
                OR BTRIM(external_id) = ''
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_properties_org_external_id
            ON properties (
                organization_id,
                external_id
            )
            WHERE external_id IS NOT NULL
                AND external_id <> ''
            """
        )

        for column_name, column_sql in (
            ("merchant", "TEXT"),
            ("receipt_number", "TEXT"),
            ("attachment_hash", "TEXT"),
            ("attachment_content_type", "TEXT"),
            ("attachment_original_name", "TEXT"),
            ("treasury_account_id", "BIGINT"),
        ):
            cursor.execute(
                f"""
                ALTER TABLE cash_movements
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        for column_name, column_sql in (
            ("exchange_rate", f"{_MONEY}"),
            ("exchange_rate_date", "TEXT"),
            ("exchange_rate_source", "TEXT"),
            ("equivalent_amount_ars", f"{_MONEY}"),
            ("payment_method", "TEXT"),
            ("reference_text", "TEXT"),
            ("notes", "TEXT"),
            ("period_label", "TEXT"),
            ("cancelled_at", "TEXT"),
            ("cancelled_by_user_id", "BIGINT"),
            ("cancellation_reason", "TEXT"),
            ("is_internal_reversal", f"{_FLAG} NOT NULL DEFAULT 0"),
        ):
            cursor.execute(
                f"""
                ALTER TABLE agent_account_movements
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        cursor.execute(
            """
            UPDATE agent_account_movements
            SET is_internal_reversal = 1
            WHERE reversed_movement_id IS NOT NULL
                AND COALESCE(is_internal_reversal, 0) = 0
            """
        )

        cursor.execute(
            """
            UPDATE agent_account_movements AS original
            SET
                cancellation_reason = rev.reversal_reason,
                cancelled_at = rev.created_at,
                cancelled_by_user_id = rev.created_by_user_id
            FROM agent_account_movements AS rev
            WHERE rev.reversed_movement_id = original.id
                AND original.status = 'reversed'
                AND (
                    original.cancellation_reason IS NULL
                    OR BTRIM(original.cancellation_reason) = ''
                )
            """
        )

        for column_name, column_sql in (
            ("charge_category", "TEXT"),
            ("net_amount", f"{_MONEY}"),
            ("vat_rate", f"{_MONEY}"),
            ("vat_amount", f"{_MONEY}"),
            ("gross_amount", f"{_MONEY}"),
            ("billing_period", "TEXT"),
            ("recurring", f"{_FLAG} NOT NULL DEFAULT 0"),
            ("recurrence_type", "TEXT DEFAULT 'one_time'"),
        ):
            cursor.execute(
                f"""
                ALTER TABLE agent_account_movements
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        for column_name, column_sql in (
            ("commission_side", "TEXT"),
            ("commission_purpose", "TEXT"),
            ("commission_source_amount", f"{_MONEY}"),
            ("commission_source_currency", "TEXT"),
        ):
            cursor.execute(
                f"""
                ALTER TABLE agent_account_movements
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        cursor.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS
            idx_aa_active_operation_commission
            ON agent_account_movements (
                organization_id,
                source_id,
                agent_id,
                commission_side,
                commission_purpose
            )
            WHERE movement_type = 'commission'
                AND source_type = 'operation'
                AND status = 'confirmed'
                AND commission_side IS NOT NULL
                AND commission_purpose IS NOT NULL
            """
        )
        cursor.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS
            idx_aa_active_operation_commission_consolidated
            ON agent_account_movements (
                organization_id,
                source_id,
                agent_id,
                commission_purpose
            )
            WHERE movement_type = 'commission'
                AND source_type = 'operation'
                AND status = 'confirmed'
                AND commission_purpose = 'own_commission'
            """
        )

        cursor.execute(
            """
            UPDATE agent_account_movements
            SET gross_amount = amount
            WHERE gross_amount IS NULL
            """
        )
        cursor.execute(
            """
            UPDATE agent_account_movements
            SET net_amount = amount
            WHERE net_amount IS NULL
            """
        )
        cursor.execute(
            """
            UPDATE agent_account_movements
            SET vat_amount = 0
            WHERE vat_amount IS NULL
            """
        )
        cursor.execute(
            """
            UPDATE agent_account_movements
            SET vat_rate = 0
            WHERE vat_rate IS NULL
            """
        )
        cursor.execute(
            """
            UPDATE agent_account_movements
            SET recurrence_type = 'one_time'
            WHERE recurrence_type IS NULL
                OR BTRIM(recurrence_type) = ''
            """
        )
        cursor.execute(
            """
            UPDATE agent_account_movements
            SET billing_period = period_label
            WHERE (billing_period IS NULL OR BTRIM(billing_period) = '')
                AND period_label IS NOT NULL
                AND BTRIM(period_label) <> ''
            """
        )

        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS agent_account_payment_allocations (
                id {_ID},
                organization_id BIGINT NOT NULL,
                payment_movement_id BIGINT NOT NULL,
                charge_movement_id BIGINT,
                currency TEXT NOT NULL,
                amount {_MONEY} NOT NULL,
                created_at TEXT NOT NULL,

                FOREIGN KEY (organization_id)
                    REFERENCES organizations(id)
                    ON DELETE RESTRICT,
                FOREIGN KEY (payment_movement_id)
                    REFERENCES agent_account_movements(id)
                    ON DELETE RESTRICT,
                FOREIGN KEY (charge_movement_id)
                    REFERENCES agent_account_movements(id)
                    ON DELETE RESTRICT,

                CHECK (currency IN ('USD', 'ARS')),
                CHECK (amount > 0)
            )
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_aa_payment_alloc_org_payment
            ON agent_account_payment_allocations (
                organization_id,
                payment_movement_id
            )
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_aa_payment_alloc_org_charge
            ON agent_account_payment_allocations (
                organization_id,
                charge_movement_id
            )
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_cash_movements_attachment_hash
            ON cash_movements (
                organization_id,
                attachment_hash
            )
            """
        )

        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS agent_payment_ai_drafts (
                id {_ID},
                organization_id BIGINT NOT NULL,
                created_by_user_id BIGINT,
                status TEXT NOT NULL DEFAULT 'processing',
                user_context_text TEXT,
                attachment_path TEXT,
                attachment_hash TEXT,
                attachment_content_type TEXT,
                attachment_original_name TEXT,
                confirm_token TEXT NOT NULL,
                idempotency_key TEXT NOT NULL,
                agent_id BIGINT,
                treasury_account_id BIGINT,
                charge_movement_id BIGINT,
                confirmed_movement_id BIGINT,
                confirmed_cash_movement_id BIGINT,
                error_message_key TEXT,
                confidence TEXT,
                provider TEXT,
                draft_json TEXT,
                resolution_json TEXT,
                fields_needing_review_json TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,

                FOREIGN KEY (organization_id)
                    REFERENCES organizations(id)
                    ON DELETE RESTRICT,
                FOREIGN KEY (created_by_user_id)
                    REFERENCES users(id)
                    ON DELETE SET NULL,
                FOREIGN KEY (agent_id)
                    REFERENCES agents(id)
                    ON DELETE SET NULL,
                FOREIGN KEY (treasury_account_id)
                    REFERENCES treasury_accounts(id)
                    ON DELETE SET NULL,
                FOREIGN KEY (charge_movement_id)
                    REFERENCES agent_account_movements(id)
                    ON DELETE SET NULL,
                FOREIGN KEY (confirmed_movement_id)
                    REFERENCES agent_account_movements(id)
                    ON DELETE SET NULL,
                FOREIGN KEY (confirmed_cash_movement_id)
                    REFERENCES cash_movements(id)
                    ON DELETE SET NULL,

                CHECK (
                    status IN (
                        'processing',
                        'review',
                        'confirmed',
                        'failed',
                        'discarded'
                    )
                ),
                UNIQUE (organization_id, confirm_token)
            )
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_agent_payment_ai_org_status
            ON agent_payment_ai_drafts (
                organization_id,
                status,
                id
            )
            """
        )

        cursor.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS
            idx_agent_payment_ai_idempotency
            ON agent_payment_ai_drafts (
                organization_id,
                idempotency_key
            )
            """
        )

        for column_name, column_sql in (
            ("invoice_amount", f"{_MONEY}"),
            ("invoice_currency", "TEXT"),
            ("invoice_exchange_rate", f"{_MONEY}"),
            ("invoice_amount_set_at", "TEXT"),
            ("invoice_amount_set_by_user_id", "BIGINT"),
        ):
            cursor.execute(
                f"""
                ALTER TABLE operations
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        for column_name, column_sql in (
            ("legal_name", "TEXT"),
            ("tax_id", "TEXT"),
            ("tax_condition", "TEXT"),
            ("fiscal_address", "TEXT"),
            ("trade_name", "TEXT"),
            ("billing_email", "TEXT"),
            (
                "default_payment_condition",
                "TEXT NOT NULL DEFAULT 'cuenta_corriente'",
            ),
            (
                "default_buyer_commission_percent",
                f"{_MONEY} DEFAULT 3",
            ),
            (
                "default_seller_commission_percent",
                f"{_MONEY} DEFAULT 3",
            ),
            (
                "default_invoice_description",
                "TEXT DEFAULT 'Asesoramiento Integral de Gestión'",
            ),
            (
                "default_invoice_service_type",
                "TEXT DEFAULT 'services'",
            ),
            (
                "default_invoice_currency",
                "TEXT DEFAULT 'ARS'",
            ),
            (
                "agents_can_invoice",
                f"{_FLAG} NOT NULL DEFAULT 1",
            ),
            (
                "office_can_invoice",
                f"{_FLAG} NOT NULL DEFAULT 1",
            ),
            (
                "default_issuer_profile_id",
                "BIGINT",
            ),
        ):
            cursor.execute(
                f"""
                ALTER TABLE organization_settings
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        cursor.execute(
            """
            ALTER TABLE agent_billing_profiles
            ADD COLUMN IF NOT EXISTS
            is_active SMALLINT NOT NULL DEFAULT 1
            """
        )

        for table_name in (
            "billing_issuer_profiles",
            "agent_billing_profiles",
        ):
            for column_name, column_sql in (
                (
                    "arca_connection_status",
                    "TEXT NOT NULL DEFAULT 'not_configured'",
                ),
                ("arca_environment", "TEXT"),
                ("arca_point_of_sale", "TEXT"),
                ("arca_voucher_types", "TEXT"),
                ("arca_last_validated_at", "TEXT"),
                ("arca_certificate_ref", "TEXT"),
                ("arca_provider", "TEXT DEFAULT 'arca'"),
                ("arca_metadata", "TEXT"),
            ):
                cursor.execute(
                    f"""
                    ALTER TABLE {table_name}
                    ADD COLUMN IF NOT EXISTS
                    {column_name} {column_sql}
                    """
                )

        cursor.execute(
            """
            UPDATE organization_settings
            SET default_issuer_profile_id = sub.profile_id
            FROM (
                SELECT
                    bip.organization_id,
                    MIN(bip.id) AS profile_id
                FROM billing_issuer_profiles bip
                WHERE bip.is_default = 1
                    AND bip.is_active = 1
                GROUP BY bip.organization_id
            ) AS sub
            WHERE organization_settings.organization_id
                = sub.organization_id
                AND organization_settings.default_issuer_profile_id
                    IS NULL
            """
        )

        for column_name, column_sql in (
            ("side", "TEXT"),
            ("issuer_profile_id", "BIGINT"),
            ("issuer_key", "TEXT"),
            ("recipient_party_id", "BIGINT"),
            (
                "origin_type",
                "TEXT NOT NULL DEFAULT 'operation'",
            ),
            ("agent_account_movement_id", "BIGINT"),
            (
                "invoice_purpose",
                "TEXT NOT NULL DEFAULT 'standard'",
            ),
            ("charge_linked_at", "TEXT"),
            ("charge_linked_by_user_id", "BIGINT"),
            (
                "vat_rate",
                f"{_MONEY} NOT NULL DEFAULT 0",
            ),
        ):
            cursor.execute(
                f"""
                ALTER TABLE invoices
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        cursor.execute(
            """
            ALTER TABLE invoices
            ALTER COLUMN operation_id DROP NOT NULL
            """
        )
        cursor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_invoices_agent_account_movement'
                ) THEN
                    ALTER TABLE invoices
                    ADD CONSTRAINT fk_invoices_agent_account_movement
                    FOREIGN KEY (agent_account_movement_id)
                    REFERENCES agent_account_movements(id)
                    ON DELETE RESTRICT;
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_invoices_charge_linked_user'
                ) THEN
                    ALTER TABLE invoices
                    ADD CONSTRAINT fk_invoices_charge_linked_user
                    FOREIGN KEY (charge_linked_by_user_id)
                    REFERENCES users(id)
                    ON DELETE SET NULL;
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'ck_invoices_origin_type'
                ) THEN
                    ALTER TABLE invoices
                    ADD CONSTRAINT ck_invoices_origin_type
                    CHECK (
                        origin_type IN (
                            'operation', 'agent_account_charge'
                        )
                    );
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'ck_invoices_origin_relation'
                ) THEN
                    ALTER TABLE invoices
                    ADD CONSTRAINT ck_invoices_origin_relation
                    CHECK (
                        (
                            origin_type = 'operation'
                            AND operation_id IS NOT NULL
                        )
                        OR (
                            origin_type = 'agent_account_charge'
                            AND agent_account_movement_id IS NOT NULL
                        )
                    );
                END IF;
            END
            $$;
            """
        )

        from .invoice_uniqueness_migration import (
            migrate_invoices_active_uniqueness_postgres,
        )

        migrate_invoices_active_uniqueness_postgres(cursor)

        cursor.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS
            idx_invoices_one_active_per_charge
            ON invoices (
                organization_id,
                agent_account_movement_id,
                invoice_purpose
            )
            WHERE origin_type = 'agent_account_charge'
                AND status IN (
                    'draft',
                    'ready_to_issue',
                    'issued',
                    'error'
                )
            """
        )
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_invoices_charge_history
            ON invoices (
                organization_id,
                agent_account_movement_id,
                id
            )
            WHERE origin_type = 'agent_account_charge'
            """
        )

        for column_name, column_sql in (
            ("fiscal_voucher_type", "TEXT"),
            ("issued_at", "TEXT"),
            ("issued_by_user_id", "BIGINT"),
            ("provider_error", "TEXT"),
            ("fiscal_environment", "TEXT"),
            ("issue_attempt_token", "TEXT"),
        ):
            cursor.execute(
                f"""
                ALTER TABLE invoices
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS arca_ta_cache (
                cache_key TEXT PRIMARY KEY,
                token TEXT NOT NULL,
                sign TEXT NOT NULL,
                expires_at TEXT NOT NULL,
                service TEXT NOT NULL,
                cuit TEXT NOT NULL,
                environment TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )

        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS invoice_fiscal_events (
                id {_ID},
                organization_id BIGINT NOT NULL,
                invoice_id BIGINT NOT NULL,
                issuer_key TEXT,
                environment TEXT,
                event_type TEXT NOT NULL,
                result TEXT NOT NULL,
                cae TEXT,
                error_message TEXT,
                actor_user_id BIGINT,
                metadata TEXT,
                created_at TEXT NOT NULL,
                FOREIGN KEY (organization_id)
                    REFERENCES organizations(id)
                    ON DELETE RESTRICT,
                FOREIGN KEY (invoice_id)
                    REFERENCES invoices(id)
                    ON DELETE RESTRICT
            )
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_invoice_fiscal_events_invoice
            ON invoice_fiscal_events (
                organization_id,
                invoice_id,
                id
            )
            """
        )

        cursor.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS
            idx_invoices_fiscal_voucher_unique
            ON invoices (
                organization_id,
                issuer_key,
                point_of_sale,
                fiscal_voucher_type,
                external_invoice_number
            )
            WHERE status = 'issued'
                AND provider = 'arca'
                AND external_invoice_number IS NOT NULL
            """
        )

        for column_name, column_sql in (
            ("is_referred", f"{_FLAG} NOT NULL DEFAULT 0"),
            ("referred_side", "TEXT"),
            ("seller_vat_original", f"{_MONEY} NOT NULL DEFAULT 0"),
            ("buyer_vat_original", f"{_MONEY} NOT NULL DEFAULT 0"),
        ):
            cursor.execute(
                f"""
                ALTER TABLE operations
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        for column_name, column_sql in (
            ("contact_name", "TEXT"),
            ("duration_minutes", "INTEGER"),
            ("reminder_minutes", "INTEGER"),
            ("attendance_status", "TEXT"),
            ("outcome_json", "TEXT"),
            ("google_event_id", "TEXT"),
            ("contact_id", "BIGINT"),
        ):
            cursor.execute(
                f"""
                ALTER TABLE agent_tasks
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        for column_name, column_sql in (
            ("events_cache_json", "TEXT"),
            ("sync_token", "TEXT"),
            ("last_error", "TEXT"),
        ):
            cursor.execute(
                f"""
                ALTER TABLE google_calendar_connections
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        for column_name, column_sql in (
            ("listing_currency", "TEXT"),
            ("neighborhood", "TEXT"),
            ("rooms", "INTEGER"),
            ("bedrooms", "INTEGER"),
            ("bathrooms", "INTEGER"),
            ("covered_m2", f"{_MONEY}"),
            ("total_m2", f"{_MONEY}"),
            ("parking_spaces", "INTEGER"),
            ("description", "TEXT"),
            ("commercial_status", "TEXT"),
            ("features_json", "TEXT"),
        ):
            cursor.execute(
                f"""
                ALTER TABLE properties
                ADD COLUMN IF NOT EXISTS
                {column_name} {column_sql}
                """
            )

        cursor.execute(
            """
            ALTER TABLE property_change_requests
            ADD COLUMN IF NOT EXISTS
            proposed_listing_currency TEXT
            """
        )

        cursor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'ck_properties_listing_currency'
                ) THEN
                    ALTER TABLE properties
                    ADD CONSTRAINT ck_properties_listing_currency
                    CHECK (
                        listing_currency IS NULL
                        OR listing_currency IN ('USD', 'ARS')
                    );
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'ck_properties_commercial_status'
                ) THEN
                    ALTER TABLE properties
                    ADD CONSTRAINT ck_properties_commercial_status
                    CHECK (
                        commercial_status IS NULL
                        OR commercial_status IN (
                            'available',
                            'reserved',
                            'sold',
                            'rented',
                            'withdrawn'
                        )
                    );
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname
                        = 'ck_pcr_proposed_listing_currency'
                ) THEN
                    ALTER TABLE property_change_requests
                    ADD CONSTRAINT ck_pcr_proposed_listing_currency
                    CHECK (
                        proposed_listing_currency IS NULL
                        OR proposed_listing_currency IN ('USD', 'ARS')
                    );
                END IF;
            END
            $$;
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_properties_org_commercial
            ON properties (organization_id, commercial_status)
            """
        )
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_properties_org_neighborhood
            ON properties (organization_id, neighborhood)
            """
        )
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_properties_org_purpose_currency
            ON properties (
                organization_id,
                listing_purpose,
                listing_currency
            )
            """
        )

        cursor.execute(
            """
            UPDATE properties
            SET listing_currency = unique_src.listing_currency
            FROM (
                SELECT
                    property_id,
                    MIN(listing_currency) AS listing_currency
                FROM property_external_listings
                WHERE listing_currency IN ('USD', 'ARS')
                GROUP BY property_id
                HAVING COUNT(DISTINCT listing_currency) = 1
            ) AS unique_src
            WHERE properties.id = unique_src.property_id
                AND (
                    properties.listing_currency IS NULL
                    OR BTRIM(properties.listing_currency) = ''
                )
            """
        )

        if not _schema_version_applied(
            cursor,
            POSTGRES_SCHEMA_VERSION,
        ):
            from .treasury_accounts_repository import (
                ensure_legacy_default_accounts,
            )

            cursor.execute(
                """
                SELECT id FROM organizations
                """
            )
            for org_row in cursor.fetchall():
                ensure_legacy_default_accounts(
                    cursor,
                    org_row[0],
                )

            cursor.execute(
                """
                SELECT DISTINCT organization_id
                FROM cash_movements
                """
            )
            for org_row in cursor.fetchall():
                ensure_legacy_default_accounts(
                    cursor,
                    org_row[0],
                )

            _record_schema_version(
                cursor,
                POSTGRES_SCHEMA_VERSION,
            )

        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()
