"""
Clean PostgreSQL schema for the current final application model.

This is NOT a port of SQLite migrate_schema() history (no PRAGMA,
no table rebuilds). Apply once via create_postgres_schema().

Type policy (Phase 2):
- IDs: BIGINT GENERATED BY DEFAULT AS IDENTITY
- Money / rates / percents: NUMERIC(18,4) — no 2-decimal truncation in DB
- Flags (is_active, is_read, registration_enabled): SMALLINT 0/1
  to match existing repository writes (`1 if flag else 0`) and
  predicates (`= 0` / `= 1`) without conversion layers
- Timestamps and operation_date: TEXT (ISO / DD/MM/YYYY) for
  compatibility; operation_date is NOT migrated to DATE yet
"""

from __future__ import annotations

from modules.database.connection import get_connection


POSTGRES_SCHEMA_VERSION = "postgres_v1"

# Money / calculation columns use NUMERIC(18,4).
_MONEY = "NUMERIC(18, 4)"
_ID = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
_FLAG = "SMALLINT"


SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS schema_migrations (
        version TEXT PRIMARY KEY,
        applied_at TEXT NOT NULL
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS organizations (
        id {_ID},
        name TEXT NOT NULL,
        is_active {_FLAG} NOT NULL DEFAULT 1
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS organization_settings (
        organization_id BIGINT PRIMARY KEY,
        display_name TEXT NOT NULL,
        default_language TEXT NOT NULL DEFAULT 'es',
        default_currency TEXT NOT NULL DEFAULT 'USD',
        timezone TEXT NOT NULL
            DEFAULT 'America/Argentina/Buenos_Aires',
        logo_path TEXT,
        accent_color TEXT,
        registration_code_hash TEXT,
        registration_enabled {_FLAG} NOT NULL DEFAULT 1,
        registration_code_rotated_at TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE CASCADE
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS agents (
        id {_ID},
        name TEXT NOT NULL,
        type TEXT NOT NULL,
        organization_id BIGINT NOT NULL,
        external_provider TEXT,
        external_id TEXT,
        last_synced_at TEXT,
        team_leader_agent_id BIGINT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (team_leader_agent_id)
            REFERENCES agents(id)
            ON DELETE SET NULL
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_agents_team_leader
    ON agents (organization_id, team_leader_agent_id)
    WHERE team_leader_agent_id IS NOT NULL
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_agents_org_external_identity
    ON agents (
        organization_id,
        external_provider,
        external_id
    )
    WHERE external_provider IS NOT NULL
        AND external_id IS NOT NULL
        AND external_id <> ''
    """,
    f"""
    CREATE TABLE IF NOT EXISTS properties (
        id {_ID},
        address TEXT NOT NULL,
        jurisdiction TEXT NOT NULL,
        organization_id BIGINT NOT NULL,
        agent_id BIGINT,
        property_type TEXT,
        listing_price {_MONEY},
        listing_purpose TEXT,
        last_synced_at TEXT,
        status TEXT NOT NULL DEFAULT 'approved',
        rejection_reason TEXT,
        reviewed_by_user_id BIGINT,
        reviewed_at TEXT,
        created_by_user_id BIGINT,
        submitted_at TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE RESTRICT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS operations (
        id {_ID},
        operation_date TEXT NOT NULL,
        agent_id BIGINT NOT NULL,
        property_id BIGINT NOT NULL,
        organization_id BIGINT NOT NULL,
        was_invoiced TEXT NOT NULL,
        invoice_full_commission TEXT NOT NULL DEFAULT 'no',
        vat_amount {_MONEY} NOT NULL,
        sale_price {_MONEY} NOT NULL,
        commission_rate {_MONEY} NOT NULL,
        total_commission {_MONEY} NOT NULL,
        commission_after_abao {_MONEY} NOT NULL,
        abao {_MONEY} NOT NULL,
        martillero {_MONEY} NOT NULL,
        agent_payment {_MONEY} NOT NULL,
        office_payment {_MONEY} NOT NULL,
        office_total {_MONEY} NOT NULL,
        currency TEXT NOT NULL DEFAULT 'USD',
        original_amount {_MONEY},
        exchange_rate {_MONEY} NOT NULL DEFAULT 1,
        status TEXT NOT NULL DEFAULT 'approved',
        rejection_reason TEXT,
        created_by_user_id BIGINT,
        reviewed_by_user_id BIGINT,
        reviewed_at TEXT,

        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (property_id)
            REFERENCES properties(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS users (
        id {_ID},
        username TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL,
        agent_id BIGINT,
        is_active {_FLAG} NOT NULL DEFAULT 1,
        organization_id BIGINT NOT NULL,
        email TEXT,
        first_name TEXT,
        last_name TEXT,
        phone TEXT,
        account_status TEXT NOT NULL DEFAULT 'active',

        UNIQUE (organization_id, username),

        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE SET NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS registration_requests (
        id {_ID},
        organization_id BIGINT NOT NULL,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT NOT NULL,
        phone TEXT,
        password_hash TEXT NOT NULL,
        status TEXT NOT NULL,
        rejection_reason TEXT,
        reviewed_by_user_id BIGINT,
        reviewed_at TEXT,
        created_at TEXT NOT NULL,
        email_verified_at TEXT,
        approved_user_id BIGINT,
        approved_agent_id BIGINT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS email_verification_tokens (
        id {_ID},
        registration_request_id BIGINT NOT NULL,
        token_hash TEXT NOT NULL,
        expires_at TEXT NOT NULL,
        used_at TEXT,
        created_at TEXT NOT NULL,
        attempt_count INTEGER NOT NULL DEFAULT 0,
        invalidated_at TEXT,
        last_sent_at TEXT,

        FOREIGN KEY (registration_request_id)
            REFERENCES registration_requests(id)
            ON DELETE CASCADE
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS organization_guest_access (
        id {_ID},
        organization_id BIGINT NOT NULL,
        token_hash TEXT NOT NULL UNIQUE,
        label TEXT,
        created_by_user_id BIGINT,
        created_at TEXT NOT NULL,
        expires_at TEXT,
        revoked_at TEXT,
        last_used_at TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE CASCADE
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS notifications (
        id {_ID},
        organization_id BIGINT NOT NULL,
        user_id BIGINT NOT NULL,
        kind TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        entity_id BIGINT NOT NULL,
        payload_json TEXT,
        is_read {_FLAG} NOT NULL DEFAULT 0,
        actor_user_id BIGINT,
        created_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS operation_documents (
        id {_ID},
        organization_id BIGINT NOT NULL,
        operation_id BIGINT NOT NULL,
        doc_type TEXT NOT NULL,
        stored_name TEXT NOT NULL,
        original_filename TEXT NOT NULL,
        content_type TEXT NOT NULL,
        size_bytes INTEGER NOT NULL,
        uploaded_by_user_id BIGINT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (operation_id)
            REFERENCES operations(id)
            ON DELETE CASCADE,

        FOREIGN KEY (uploaded_by_user_id)
            REFERENCES users(id)
            ON DELETE RESTRICT,

        CHECK (
            doc_type IN (
                'martillero_client',
                'agent_client',
                'uif_form',
                'uif_additional',
                'transfer_receipt',
                'reservation_deposit',
                'deed_contract',
                'other'
            )
        )
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_operation_documents_structured_unique
    ON operation_documents (
        organization_id,
        operation_id,
        doc_type
    )
    WHERE doc_type <> 'other'
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_operation_documents_org_operation
    ON operation_documents (
        organization_id,
        operation_id
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_operation_documents_operation
    ON operation_documents (operation_id)
    """,
    f"""
    CREATE TABLE IF NOT EXISTS property_change_requests (
        id {_ID},
        organization_id BIGINT NOT NULL,
        property_id BIGINT NOT NULL,
        requested_by_user_id BIGINT NOT NULL,
        proposed_address TEXT NOT NULL,
        proposed_jurisdiction TEXT NOT NULL,
        proposed_agent_id BIGINT,
        status TEXT NOT NULL,
        rejection_reason TEXT,
        reviewed_by_user_id BIGINT,
        reviewed_at TEXT,
        created_at TEXT NOT NULL,
        proposed_property_type TEXT,
        proposed_listing_price {_MONEY},
        proposed_listing_purpose TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (property_id)
            REFERENCES properties(id)
            ON DELETE RESTRICT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS property_external_listings (
        id {_ID},
        organization_id BIGINT NOT NULL,
        property_id BIGINT NOT NULL,
        provider TEXT NOT NULL,
        provider_label TEXT,
        external_id TEXT,
        url TEXT,
        status TEXT NOT NULL,
        listing_currency TEXT,
        buyer_side_commission_percent {_MONEY},
        seller_side_commission_percent {_MONEY},
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        last_synced_at TEXT,
        created_by_user_id BIGINT,
        updated_by_user_id BIGINT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (property_id)
            REFERENCES properties(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,

        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,

        CHECK (
            provider IN (
                'remax_web',
                'organization_website',
                'zonaprop',
                'argenprop',
                'mercadolibre',
                'other'
            )
        ),
        CHECK (
            status IN (
                'active',
                'paused',
                'reserved',
                'negotiation',
                'sold',
                'inactive'
            )
        ),
        CHECK (
            listing_currency IS NULL
            OR listing_currency IN ('USD', 'ARS')
        ),
        CHECK (
            url IS NULL
            OR url LIKE 'http://%'
            OR url LIKE 'https://%'
        )
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_property_external_listings_org_property
    ON property_external_listings (
        organization_id,
        property_id
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_property_external_listings_org_provider
    ON property_external_listings (
        organization_id,
        provider
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_property_external_listings_structured_provider
    ON property_external_listings (
        organization_id,
        property_id,
        provider
    )
    WHERE provider <> 'other'
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_property_external_listings_external_id
    ON property_external_listings (
        organization_id,
        provider,
        external_id
    )
    WHERE external_id IS NOT NULL
        AND external_id <> ''
    """,
    f"""
    CREATE TABLE IF NOT EXISTS organization_integrations (
        id {_ID},
        organization_id BIGINT NOT NULL,
        provider TEXT NOT NULL,
        scope_type TEXT NOT NULL,
        agent_id BIGINT,
        status TEXT NOT NULL DEFAULT 'disconnected',
        external_office_id TEXT,
        config_json TEXT,
        last_synced_at TEXT,
        last_sync_status TEXT,
        last_sync_error TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE RESTRICT,

        CHECK (
            provider IN (
                'remax',
                'organization_website',
                'stub_fixture',
                'csv_upload'
            )
        ),
        CHECK (
            scope_type IN ('organization', 'agent')
        ),
        CHECK (
            status IN (
                'disconnected',
                'connected',
                'error',
                'disabled'
            )
        ),
        CHECK (
            last_sync_status IS NULL
            OR last_sync_status IN ('ok', 'partial', 'failed')
        ),
        CHECK (
            (
                scope_type = 'organization'
                AND agent_id IS NULL
            )
            OR (
                scope_type = 'agent'
                AND agent_id IS NOT NULL
            )
        )
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_org_integrations_org_provider_org_scope
    ON organization_integrations (
        organization_id,
        provider
    )
    WHERE scope_type = 'organization'
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS
    idx_org_integrations_org_provider_agent_scope
    ON organization_integrations (
        organization_id,
        provider,
        agent_id
    )
    WHERE scope_type = 'agent'
        AND agent_id IS NOT NULL
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_org_integrations_organization
    ON organization_integrations (organization_id)
    """,
    """
    CREATE TABLE IF NOT EXISTS csv_import_batches (
        id TEXT PRIMARY KEY,
        organization_id BIGINT NOT NULL,
        filename TEXT,
        payload_json TEXT NOT NULL,
        preview_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        expires_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE CASCADE
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_csv_import_batches_organization
    ON csv_import_batches (organization_id)
    """,
    f"""
    CREATE TABLE IF NOT EXISTS integration_sync_runs (
        id {_ID},
        organization_id BIGINT NOT NULL,
        integration_id BIGINT NOT NULL,
        started_at TEXT NOT NULL,
        finished_at TEXT,
        status TEXT NOT NULL,
        agents_created INTEGER NOT NULL DEFAULT 0,
        agents_updated INTEGER NOT NULL DEFAULT 0,
        properties_created INTEGER NOT NULL DEFAULT 0,
        properties_updated INTEGER NOT NULL DEFAULT 0,
        listings_created INTEGER NOT NULL DEFAULT 0,
        listings_updated INTEGER NOT NULL DEFAULT 0,
        listings_deactivated INTEGER NOT NULL DEFAULT 0,
        error_summary TEXT,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (integration_id)
            REFERENCES organization_integrations(id)
            ON DELETE CASCADE,

        CHECK (
            status IN ('running', 'ok', 'partial', 'failed')
        )
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS
    idx_integration_sync_runs_integration
    ON integration_sync_runs (
        integration_id,
        started_at
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS agent_wallet_movements (
        id {_ID},
        organization_id BIGINT NOT NULL,
        agent_id BIGINT NOT NULL,
        operation_id BIGINT,
        movement_type TEXT NOT NULL,
        amount {_MONEY} NOT NULL,
        currency TEXT NOT NULL DEFAULT 'USD',
        source_agent_id BIGINT,
        related_movement_id BIGINT,
        description TEXT,
        reference TEXT,
        idempotency_key TEXT,
        created_at TEXT NOT NULL,

        FOREIGN KEY (organization_id)
            REFERENCES organizations(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (agent_id)
            REFERENCES agents(id)
            ON DELETE RESTRICT,

        FOREIGN KEY (operation_id)
            REFERENCES operations(id)
            ON DELETE SET NULL,

        FOREIGN KEY (source_agent_id)
            REFERENCES agents(id)
            ON DELETE SET NULL,

        FOREIGN KEY (related_movement_id)
            REFERENCES agent_wallet_movements(id)
            ON DELETE SET NULL,

        CHECK (
            movement_type IN (
                'own_commission',
                'team_leader_income',
                'adjustment',
                'reversal'
            )
        ),
        CHECK (currency IN ('USD', 'ARS'))
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS idx_wallet_idempotency
    ON agent_wallet_movements (
        organization_id,
        idempotency_key
    )
    WHERE idempotency_key IS NOT NULL
        AND idempotency_key <> ''
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_wallet_agent
    ON agent_wallet_movements (
        organization_id,
        agent_id,
        created_at
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_wallet_operation
    ON agent_wallet_movements (
        organization_id,
        operation_id
    )
    """,
)


POSTGRES_TABLES = (
    "schema_migrations",
    "organizations",
    "organization_settings",
    "agents",
    "properties",
    "operations",
    "users",
    "registration_requests",
    "email_verification_tokens",
    "organization_guest_access",
    "notifications",
    "operation_documents",
    "property_change_requests",
    "property_external_listings",
    "organization_integrations",
    "csv_import_batches",
    "integration_sync_runs",
    "agent_wallet_movements",
)


def _schema_version_applied(cursor, version):
    cursor.execute(
        """
        SELECT 1
        FROM schema_migrations
        WHERE version = ?
        """,
        (version,),
    )
    return cursor.fetchone() is not None


def _record_schema_version(cursor, version):
    from datetime import datetime

    applied_at = datetime.utcnow().replace(
        microsecond=0
    ).isoformat()

    cursor.execute(
        """
        INSERT INTO schema_migrations (
            version,
            applied_at
        )
        VALUES (?, ?)
        ON CONFLICT (version) DO NOTHING
        """,
        (version, applied_at),
    )


def create_postgres_schema():
    """
    Idempotently create the PostgreSQL application schema.

    Safe to run repeatedly. Does not run SQLite migrations.
    """
    connection = get_connection()
    cursor = connection.cursor()

    try:
        for statement in SCHEMA_STATEMENTS:
            cursor.execute(statement)

        if not _schema_version_applied(
            cursor,
            POSTGRES_SCHEMA_VERSION,
        ):
            _record_schema_version(
                cursor,
                POSTGRES_SCHEMA_VERSION,
            )

        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()
