"""Per-user push category preferences. Idempotent SQLite + Postgres."""

from __future__ import annotations

from modules.config import BACKEND_POSTGRES, get_database_backend
from modules.database.connection import get_connection


SQLITE_DDL = """
CREATE TABLE IF NOT EXISTS user_notification_preferences (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    push_visit_reminders INTEGER NOT NULL DEFAULT 1,
    push_invoice_ready INTEGER NOT NULL DEFAULT 1,
    push_property_matches INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL,
    UNIQUE (organization_id, user_id),
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)
"""

POSTGRES_DDL = """
CREATE TABLE IF NOT EXISTS user_notification_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    push_visit_reminders SMALLINT NOT NULL DEFAULT 1,
    push_invoice_ready SMALLINT NOT NULL DEFAULT 1,
    push_property_matches SMALLINT NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL,
    UNIQUE (organization_id, user_id),
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)
"""

SQLITE_INDEXES = (
    "CREATE INDEX IF NOT EXISTS idx_user_notification_prefs_org_user "
    "ON user_notification_preferences (organization_id, user_id)",
)

POSTGRES_INDEXES = SQLITE_INDEXES


def migrate_user_notification_preferences_sqlite():
    connection = get_connection()
    try:
        cursor = connection.cursor()
        cursor.execute(SQLITE_DDL)
        for statement in SQLITE_INDEXES:
            cursor.execute(statement)
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def migrate_user_notification_preferences_postgres(cursor):
    cursor.execute(POSTGRES_DDL)
    for statement in POSTGRES_INDEXES:
        cursor.execute(statement)


def migrate_user_notification_preferences():
    if get_database_backend() == BACKEND_POSTGRES:
        connection = get_connection()
        try:
            cursor = connection.cursor()
            migrate_user_notification_preferences_postgres(cursor)
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()
        return
    migrate_user_notification_preferences_sqlite()
