"""Heartbeat of visit-reminder scans. Cron vs admin QA. Idempotent."""

from __future__ import annotations

from modules.config import BACKEND_POSTGRES, get_database_backend
from modules.database.connection import get_connection


SQLITE_DDL = """
CREATE TABLE IF NOT EXISTS visit_reminder_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL,
    source TEXT NOT NULL,
    ran_at TEXT NOT NULL,
    candidate_count INTEGER NOT NULL DEFAULT 0,
    dispatched INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT
)
"""

POSTGRES_DDL = """
CREATE TABLE IF NOT EXISTS visit_reminder_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    source TEXT NOT NULL,
    ran_at TEXT NOT NULL,
    candidate_count INTEGER NOT NULL DEFAULT 0,
    dispatched INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT
)
"""

INDEXES = (
    "CREATE INDEX IF NOT EXISTS idx_visit_reminder_runs_org_source_ran "
    "ON visit_reminder_runs (organization_id, source, ran_at)",
)


def migrate_visit_reminder_runs_sqlite():
    connection = get_connection()
    try:
        cursor = connection.cursor()
        cursor.execute(SQLITE_DDL)
        for statement in INDEXES:
            cursor.execute(statement)
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def migrate_visit_reminder_runs_postgres(cursor):
    cursor.execute(POSTGRES_DDL)
    for statement in INDEXES:
        cursor.execute(statement)


def migrate_visit_reminder_runs():
    if get_database_backend() == BACKEND_POSTGRES:
        connection = get_connection()
        try:
            cursor = connection.cursor()
            migrate_visit_reminder_runs_postgres(cursor)
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()
        return
    migrate_visit_reminder_runs_sqlite()
