"""Canonical intents for the transversal JRH assistant. No business logic."""

from __future__ import annotations

QUERY_PENDINGS = "QUERY_PENDINGS"
QUERY_AGENT_ACCOUNT = "QUERY_AGENT_ACCOUNT"
QUERY_AGENDA = "QUERY_AGENDA"
QUERY_PROPERTIES = "QUERY_PROPERTIES"
QUERY_PROPERTY_NEEDS = "QUERY_PROPERTY_NEEDS"
QUERY_OPERATIONS = "QUERY_OPERATIONS"
QUERY_INVOICES = "QUERY_INVOICES"
CREATE_TASK = "CREATE_TASK"
START_INVOICE = "START_INVOICE"
START_AGENT_PAYMENT = "START_AGENT_PAYMENT"
START_ACM = "START_ACM"
QUERY_ACM = "QUERY_ACM"
ACM_EXPLAIN = "ACM_EXPLAIN"
ACM_REMOVE_COMPARABLE = "ACM_REMOVE_COMPARABLE"
ACM_FILTER_COMPARABLES = "ACM_FILTER_COMPARABLES"
ACM_PRICE_SCENARIO = "ACM_PRICE_SCENARIO"
DOWNLOAD_ACM = "DOWNLOAD_ACM"
QUERY_PRODUCTIVITY = "QUERY_PRODUCTIVITY"
FALLBACK = "FALLBACK"

ALL_INTENTS = (
    QUERY_PENDINGS,
    QUERY_AGENT_ACCOUNT,
    QUERY_AGENDA,
    QUERY_PROPERTIES,
    QUERY_PROPERTY_NEEDS,
    QUERY_OPERATIONS,
    QUERY_INVOICES,
    CREATE_TASK,
    START_INVOICE,
    START_AGENT_PAYMENT,
    START_ACM,
    QUERY_ACM,
    ACM_EXPLAIN,
    ACM_REMOVE_COMPARABLE,
    ACM_FILTER_COMPARABLES,
    ACM_PRICE_SCENARIO,
    DOWNLOAD_ACM,
    QUERY_PRODUCTIVITY,
    FALLBACK,
)

FINANCIAL_ACTIONS = {START_INVOICE, START_AGENT_PAYMENT}
WRITE_ACTIONS = {
    CREATE_TASK,
    START_INVOICE,
    START_AGENT_PAYMENT,
    START_ACM,
    ACM_REMOVE_COMPARABLE,
    ACM_FILTER_COMPARABLES,
}
LOW_CONFIDENCE = 0.55
